### ISSUE TITLE
Status tracker for Exp 1

### ISSUE THREAD

**Issue by GaurangTandon** [virtual-labs/artificial-neural-networks-iiith-js#2]
- [x] - got experiment to run on Docker
- [ ] - understood all the minute details of the functionality of the experiment
- [ ] - finished implementation of the experiment in JavaScript
- [ ] - finished testing of the experiment
